DbHost:
DbUser:
DbPass:
DbName:

RedisHost:
RedisPass:

RelayChannel:
BotUsername:
BotAccessToken:
BotClientId:
SupibotApiToken:
MentionsRegex:

LoggingWebhookUrl:
ImageHostLink:
ImageHostAuth:
BlocksLink:
BlocksAuth:

# Discord channels
Mentions:
Feed:
Errors:

# Handler prefixes
BasePrefix:
AdminPrefix:
WarframePrefix:
